nobbble/config/routes.rb
Rails.application.routes.draw do
  resources :projxes do
  	resources :bscenes
  end

  devise_for :users

  root "projxes#index"

  resources :messages, only: [:create, :new, :index]

  resources :users

end

nobbble/app/models/bscene.rb
class Bscene < ActiveRecord::Base
	belongs_to :projx
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	has_attached_file :video, styles: {
	    :medium => {
	      :geometry => "640x480",
	      :format => 'mp4'
	    },
	    :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 10}
  	}, :processors => [:transcoder]

end

nobbble/app/models/bscnene.rb
class Bscnene < ActiveRecord::Base
  belongs_to :projx
  belongs_to :user
end

nobbble/app/models/message.rb
class Message < ActiveRecord::Base
	attr_reader :user_tokens

	belongs_to :sender, class_name: 'User'
	has_many :recipients
	has_many :users, :through => :recipients

	validates :sender_id, presence: true
	validates :title, presence: true
	validates :description, presence: true
	validates :budget, presence: true
	validates :location, presence: true
	validates :date, presence: true
	validates :start_time, presence: true
	validates :end_time, presence: true
	validates :skill, presence: true


	def user_tokens=(ids)
		self.user_ids = ids
	end

end

nobbble/app/models/projx.rb
class Projx < ActiveRecord::Base
 	belongs_to :user
 	has_many :bscenes, dependent: :destroy
 	acts_as_votable
 	validates :title, :description, :location, :type_skill, :date, presence: true


 #  	validate :user_quota, :on => :create

	# private

	# def user_quota
	# 	if user.projxes.size >= 4
	# 		errors.add(:base, "Exceeds daily limit")
	# 	elsif user.projxes.size <= 10
	# 		errors.add(:base, "Exceeds weekly limit")
	# 	end
	# end

end

nobbble/app/models/recipient.rb
class Recipient < ActiveRecord::Base
	belongs_to :message
	belongs_to :user

	validates :user_id, presence: true

	after_create :send_recipient_notification

	def send_recipient_notification
		RecipientMailer.recipient_message(user, message).deliver_now
	end
end

nobbble/app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages, foreign_key: :sender_id
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "50x50#", thumb: "30x30#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  after_create :send_notification
  has_many :projxes
  has_many :bscenes

  def send_notification
  	AdminMailer.new_user(self).deliver_now
  end

end

nobbble/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :website, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :avatar, :skill, :location, :about, :current_password, :twitter, :facebook, :instagram) }
  end
end

nobbble/app/controllers/bscenes_controller.rb
class BscenesController < ApplicationController
	before_action :authenticate_user!

	def create
		@projx = Projx.find(params[:projx_id])
		@bscene = @projx.bscenes.create(bscenes_params)

		redirect_to projx_path(@projx)
	end

	def destroy
		@projx = Projx.find params[:projx_id]
		@bscene = @projx.bscenes.find params[:id]
		@bscene.destroy
		redirect_to projx_path(@projx)
	end

	private

	def bscenes_params
		params.require(:bscene).permit(:video)
	end

end

nobbble/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!, except: [:new]

	def new
		@message = Message.new
		@recipients = User.all
		@recipient = User.find_by(id: params[:to].to_i) if params[:to]
		# @active = params[:active] == 'true' if params[:active].present?
		@chosen_recipient = User.find_by(id: params[:to].to_i) if params[:to]
		@user = User.find_by(id: params[:user])
	end



	def create
		@user = current_user

		@message = current_user.messages.build(message_params)
		if @message.save

			MessageMailer.message_created(@user).deliver_now

			flash[:success] = "Message Sent!"
			redirect_to user_path(@user)
		else
			flash[:alert] = "Nothing Happend!"
			render 'new'
		end
	end

	def index
		@messages = Recipient.where(:user_id => current_user.id).order('created_at DESC')
	end


	private

	def message_params
		params.require(:message).permit(:title, :description, :budget, :location, :date, :userskill, :start_time, :end_time, :skill, :sender_id, user_tokens: [])
	end

end

nobbble/app/controllers/projxes_controller.rb
class ProjxesController < ApplicationController
  
  before_action :authenticate, except: [:show]

  # GET /projxes
  # GET /projxes.json
  def index
    @projxes = Projx.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    @users = User.all
  end

  # GET /projxes/1
  # GET /projxes/1.json
  def show
    # @projx = Projx.find(params[:id])
    @projx = Projx.where(created_at: 10.days.ago..Time.now).find(params[:id])
    @bscenes = Bscene.where(projx_id: @projx)
  end

  # GET /projxes/new
  def new
    @projx = current_user.projxes.build
  end

  # GET /projxes/1/edit
  def edit
    @projx = Projx.find(params[:id])
  end

  # POST /projxes
  # POST /projxes.json
  def create
    @projx = current_user.projxes.build(projx_params)
    respond_to do |format|
      if @projx.save
        format.html { redirect_to @projx, notice: 'Projx was successfully created.' }
        format.json { render :show, status: :created, location: @projx }
      else
        format.html { render :new }
        format.json { render json: @projx.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projxes/1
  # PATCH/PUT /projxes/1.json
  def update
    @projx = Projx.find(params[:id])
    respond_to do |format|

      if @projx.update(projx_params)
        format.html { redirect_to @projx, notice: 'Projx was successfully updated.' }
        format.json { render :show, status: :ok, location: @projx }
      else
        format.html { render :edit }
        format.json { render json: @projx.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projxes/1
  # DELETE /projxes/1.json
  def destroy

    @projx = Projx.find(params[:id])
    @user = current_user
    if @projx.destroy
      redirect_to user_path(@user)
    end
  end

  # def upvote
  #   @projx = Projx.find(params[:id])
  #   @projx.upvote_by current_user
  #   redirect_to :back
  # end


  private

  def authenticate
    :authenticate_user! && current_user.try(:admin?)
  end
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
  def projx_params
    params.require(:projx).permit(:title, :type_skill, :location, :description, :website, :date, :stime, :etime, :user_id)
  end
end

nobbble/app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
end

nobbble/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@users = User.all
	end

	def show
	  @user = User.find(params[:id])
	end

end

nobbble/app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

	before_action :authenticate_user!

	def index
	end

end

nobbble/app/helpers/application_helper.rb
module ApplicationHelper
end

nobbble/app/helpers/bscenes_helper.rb
module BscenesHelper
end

nobbble/app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient)
    s = ''

    User.all.each do |user|
      s << "<option value='#{user.id} #{'selected' if user = chosen_recipient}>#{user.username}</option>"
    end
    s = "".html_safe
  end
end

nobbble/app/helpers/projxes_helper.rb
module ProjxesHelper
end

nobbble/app/helpers/recipients_helper.rb
module RecipientsHelper
end

nobbble/app/helpers/users_helper.rb
module UsersHelper
end

nobbble/app/helpers/welcomes_helper.rb
module WelcomesHelper
end

nobbble/app/views/bscenes/_bscene.html.erb
<!-- <= bscene.content %> -->

nobbble/app/views/bscenes/_form.html.erb
<%= form_for([@projx, @projx.bscenes.build]) do |f| %>

	<br />
	<%= f.label :video %>
	<%= f.file_field :video, class: "form-control" %>

<!-- 	<= f.text_field :content, placeholder: "Content" %> -->
	<div class="actions">
		<%= f.submit "Upload Image", class: "btn btn-primary btn-block"  %>
	</div>
<% end %>

nobbble/app/views/messages/_recipients.html.erb
<div class="project-p">
<div class="container">
  	<div class="logy">
  		<%= link_to "CONTACT", current_user %>
   	</div>
<div class="project-message">
	<%= form_for :message, url: messages_path do |f| %>

	<p>
	<div class="message-form">
		<h6>
			Type of project
		</h6>
	</div>
	<%= f.select :userskill, ["Branding", "Fashion Design", "Fashion Show", "Graphic Design", "Modeling", "Photoshoot", "Post-production", "Videography", "Wedding", "Writing", "Other"], prompt: "Choose", class: "form-control" %>
	</p>

	<hr />

	<div class="message-form">
		<h6>
			What's the plan?
		</h6>
	</div>
	<p>
	<%= f.text_field :title, id: "url", placeholder: "title", class: "form-control" %>
	</p>

	<p>
	<%= f.text_area :description,  id: "url", placeholder: "Description", class: "form-control" %>
	</p>

	<hr />

	<p>
	<div class="message-form">
		<h6>
			Do you have a place in mind?
		</h6>
	</div>
	<%= f.text_field :location, id: "url", placeholder: "Location", class: "form-control" %>
	</p>

	<hr />

	<p>
	<div class="message-form">
		<h6>
			When are we going to do this?
		</h6>
	</div>
	<%= f.date_field :date, class: "form-control" %>
	</p>

	<p>
	<%= f.select :start_time, ["12 AM", "1 AM", "2 AM", "3 AM","4 AM", "5 AM", "6 AM", "7 AM", "8 AM", "9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM", "10 PM", "11 PM"], prompt: "Start-Time", class: "form-control" %>
	</p>

	<p>
	<%= f.select :end_time, ["12 AM", "1 AM", "2 AM", "3 AM","4 AM", "5 AM", "6 AM", "7 AM", "8 AM", "9 AM", "10 AM", "11 AM", "12 PM", "1 PM", "2 PM", "3 PM", "4 PM", "5 PM", "6 PM", "7 PM", "8 PM", "9 PM", "10 PM", "11 PM"], prompt: "End-Time", class: "form-control" %>
	</p>

	<hr />

	<p>
	<div class="message-form">
		<h6>
			What is it that you do?
		</h6>
	</div>
	<%= f.select :skill, ["Agency", "Creative Director", "Dancer", "Fashion Designer", "Hairstylist", "Model", "Photographer", "Project Manager", "Singer", "Videographer"], prompt: "Skill", class: "form-control" %>
	</p>

	<hr />

	<div class="message-form">
		<h6>
			Please provide me with your budget.
		</h6>
	</div>
	<div class="input-group">
	  <span class="input-group-addon">$</span>
	<%= f.text_field :budget,  id: "url", placeholder: "0", class: "form-control" %>
	  <span class="input-group-addon">.00</span>
	</div>

	<hr />

<% if @recipient %>
    <tbody>
        <tr>
        <td><%= radio_button_tag "message[user_tokens][]", @recipient.id, @message.users.include?(@recipient), id: "user#{@recipient.id}", checked: "checked" %></td>
        <td><%= @recipient.username %></td>
        </tr>
    </tbody>
<% end %> 

	<hr />

	<div>
		<%= f.button :submit, class: "btn btn-primary btn-block" %>
	</div>
</div>

<% end %>
</div>
</div>

nobbble/app/views/messages/index.html.erb
<h2>Messages</h2>
<% @messages.each do |message| %>

	<div><%= message.message.date %> | <%= message.message.start_time %> | <%= message.message.end_time %>
	</div>
	<div><%= message.message.skill %></div>
	<div><%= message.message.location %></div>
	<div><%= message.message.title %></div>
	<div><%= message.message.description %></div>
	<div><%= message.message.budget %></div>
	
	<span>From </span><%= message.message.sender.email %>

<% end %>

nobbble/app/views/messages/new.html.erb
<%= render 'messages/recipients' %>

nobbble/app/views/projxes/_form.html.erb
<div class="project-p">
<div class="container">
    <div class="logy">
      <%= link_to "NEW PROJECT", current_user %>
    </div>

<div class="container">
<%= form_for(@projx) do |f| %>
  <% if @projx.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projx.errors.count, "error") %> prohibited this projx from being saved:</h2>

      <ul>
      <% @projx.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br />
  <div class="message-form">
    <h6>
      Type of project
    </h6>
  </div>
  <%= f.select :type_skill, ["Branding", "Fashion Design", "Fashion Show", "Graphic Design", "Modeling", "Photography", "Post-production", "Videography", "Wedding", "Writing", "Other"], prompt: "Choose", class: "form-control" %>
  </p>

<div class="field">
    <div class="message-form">
      <h6>
        Project location
      </h6>
    </div>
      <%= f.select :location,[
      "Alabama, AL",
      "Alaska, AK",
      "Arizona', AZ",
      "Arkansas, AR",
      "California, CA",
      "Colorado, CO",
      "Connecticut', CT",
      "Delaware, DE",
      "District of Columbia, DC",
      "Florida, FL",
      "Georgia, GA",
      "Hawaii, HI",
      "Idaho, ID",
      "Illinois, IL",
      "Indiana, IN",
      "Iowa, IA",
      "Kansas, KS",
      "Kentucky, KY",
      "Louisiana, LA",
      "Maine, ME",
      "Maryland, MD",
      "Massachusetts, MA",
      "Michigan, MI",
      "Minnesota, MN",
      "Mississippi, MS",
      "Missouri, MO",
      "Montana, MT",
      "Nebraska, NE",
      "Nevada, NV",
      "New Hampshire, NH",
      "New Jersey, NJ",
      "New Mexico, NM",
      "New York, NY",
      "North Carolina, NC",
      "North Dakota, ND",
      "Ohio, OH",
      "Oklahoma, OK",
      "Oregon', 'OR",
      "Pennsylvania, PA",
      "Puerto Rico, PR",
      "Rhode Island, RI",
      "South Carolina, SC",
      "South Dakota, SD",
      "Tennessee, TN",
      "Texas, TX",
      "Utah, UT",
      "Vermont, VT",
      "Virginia, VA",
      "Washington, WA",
      "West Virginia, WV",
      "Wisconsin', WI",
      "Wyoming, WY"], prompt: "Choose", class: "form-control" %>
    </div>

  <div class="field">
    <div class="message-form">
      <h6>
        Title
      </h6>
    </div>
    <%= f.text_field :title, class: "form-control", maxlength: 88 %>
  </div>
  <div class="field">
    <div class="message-form">
      <h6>
        What's your project about?
      </h6>
    </div>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="field">
    <div class="message-form">
      <h6>
        Your Website
      </h6>
    </div>
    <%= f.text_field :website, class: "form-control" %>
  </div>

  <div class="field">
    <div class="message-form">
      <h6>
        Project Date
      </h6>
    </div>
    <%= f.date_field :date, class: "form-control" %>
  </div>
  <hr />
  <div>
    <%= f.button :submit, class: "btn btn-primary btn-block" %>
  </div>
<% end %>
</div>
</div>
</div>

nobbble/app/views/projxes/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @projx %> |
<%= link_to 'Back', projxes_path %>

nobbble/app/views/projxes/index.html.erb
<% if user_signed_in? %>

<p id="notice"><%= notice %></p>
<div class="container">
<br />
<% if current_user.try(:admin?) %>
	<%= link_to 'Create Project', new_projx_path,
	class: 'btn btn-primary btn-block', style:"border-radius:400px" %>
<% else %>

<% end %>
</div>

<div class="edituserheader">
</div>
<div class ="container">
<div class="col-md-4 col-sm-12 col-xs-12">
	<% @projxes.each do |projx| %>
	<div class="type_skill">
	  <small style="
	    background-color: #6f5499;
		display: inline;
	    padding: .2em .6em .3em;
	    font-size: 75%;
	    font-weight: 700;
	    line-height: 1;
	    color: #fff;
	    text-align: center;
	    white-space: nowrap;
	    vertical-align: baseline;
	    border-radius: .25em;
	  "><%= projx.type_skill %></small>
	  <% if projx.user == current_user %>
	  <small class="pull-right" style="font-size: 15px;"><%= link_to "", projx_path(projx), method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove" %></small>
	  	<% end %>

	</div>

	<section class="panel no-border bg-success">
	<div class="panel-heading no-border container" style="
	    color: #fff;
	"><br />
	<b><%= link_to projx.title, projx_path(projx) %></b>
	</div>
	<div class="panel-body bg-white" style="
	    color: #4d4d4d; padding: 0px 15px 0px 15;
	">
	<div>
		<%= image_tag projx.user.avatar.url(:medium), style: "height:20px;width:20px; border-radius:400px;" %>
		<%= link_to projx.user.username, projx.user %>
	<small class="pull-right"><%= time_ago_in_words(projx.created_at) %> ago</small>
	</div>
	<small><%= projx.location %></small>
	</div>
	</section>
	<hr />
	<% end %>
	<div class="digg_pagination">
	    <%= will_paginate @projxes, :container => false %>
  	</div>
</div>

</div>
</div>
</div>

<% else %>
	<!-- Start intro / Video version -->
		<section class="video-hero">
			<div class="section-overlay">
				<div class="float-content">
					<div class="container">
						<div class="row">
							<div class="col-sm-8 col-sm-offset-2 text-center">
								<br>
								<div class="loga">
								  <strong><%= link_to "CONNECT•CREATE&GROW", current_user, style: "color:#000;text-align:center;font-size:16px;" %></strong>
								</div>
								<div class="loga">
								  <%= link_to "SIGN IN", current_user, style: "color:#000;text-align:center;" %>
								</div>
								<br />
								<%= link_to "", new_user_session_path, class: "glyphicon glyphicon-log-in",
								style: 
								"
								background:#6f5499;
								color:#fff;
								border-radius:400px;
								height:50px;
								width:50px;
								font-size:17px;
								text-align:center;
								padding-top:17px;
								padding-right:5px;
								" %>
								<img src="/images/header-img.png" alt="" class="img-responsive" data-start="opacity: 1; margin-bottom: 0%;" data-80p="opacity: 0; margin-bottom: -15%;" style="margin-top:35px;">
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	<!-- End intro / Video version -->
	<!-- Start footer -->
		<footer>
			<div class="container">
				<div class="divide-xs"></div>
				<br />
				<div class="row text-center">
					<div class="col-sm-12 divide-xs">
						<p><small>Copyright &copy; 2015 All Offices Inc. All rights reserved.</small></p>
					</div>
				</div>
			</div>
		</footer>
<% end %>

nobbble/app/views/projxes/new.html.erb
<%= render 'form' %>

nobbble/app/views/projxes/show.html.erb
<div class="project-p">
<div class="container">

<p id="notice"><%= notice %></p>
<div class="container">

<!-- <div class="message-form">
  <h6>
    <strong>Date:</strong> <= @projx.date %>
  </h6>
</div> -->

    <div class="profile-information">
    <h5 class="name">
      <%= image_tag @projx.user.avatar.url(:medium), style: "height:40px;width:40px; border-radius:400px;" %>
      <%= link_to @projx.user.username, user_path(@projx.user) %><br />
      <small><%= @projx.location %></small>
    </h5>
<br />
   <h6>
      <span class="" aria-hidden="true"></span>
      <% if @projx.user == current_user %>
      <%= link_to '', edit_projx_path(@projx), style: "background: #000; width: 40px; height:40px; font-size: 19px; text-align:center;padding-top:9px;border-radius: 400px;background:#eee;", class: "glyphicon glyphicon-pencil" %>
      <% end %>
    </h6>
    </div>

<br />
<br />
<br />
<small style="
      background-color: #6f5499;
    display: inline;
      padding: .2em .6em .3em;
      font-size: 75%;
      font-weight: 700;
      line-height: 1;
      color: #fff;
      text-align: center;
      white-space: nowrap;
      vertical-align: baseline;
      border-radius: .25em;
    "><%= @projx.type_skill %></small>
<br />
<br />
    <strong>Title:</strong> <%= @projx.title %>

<br />
<br />

    <strong>Description:</strong> <%= @projx.description %>

<br />
<br />
<strong>Date:</strong>
<%= @projx.date %>


<br />
<br />
<div clas="container">
  <strong>Website:</strong>
<a href="" onclick="window.open(this.href); return false;" onkeypress="window.open(this.href); return false;"><%= @projx.website %></a>
</div>

</div>
  <% if @projx.user == current_user %>
    <div class="container">
      <%= render "bscenes/form" %>
    </div>
  <% end %>
</div>
</div>

<div class="container">
<div class="post_index">
  <div id="posts">
    <% @bscenes.each do |bscene| %>
    <div class="col-md-6">
    <div class="post">
    <div class="post_image" style="
    vertical-align: middle;
    max-width: 100%;
  ">
<!--     <= video_tag bscene.image.url(:small) %>
<hr /> -->
    <%= video_tag bscene.video.url(:medium), controls: true, style: "max-width: 100%;" %>

    </div>
    <% if @projx.user == current_user %>
      <div class="index-post-description">

      <span><%= link_to "Delete", [bscene.projx, bscene], method: :delete, data: { confirm: 'Are you sure?' } %></span>

      </div>
    <% end %>
    <br />
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>

<!-- Image uploads -->
<!-- 
<div class="container">
<div class="post_index">
  <div id="posts">
    < @bscenes.each do |bscene| %>
    <div class="col-md-6">
    <div class="post">
    <div class="post_image" style="
    vertical-align: middle;
    max-width: 100%;
  ">
<!--     <= video_tag bscene.image.url(:small) %>
<hr /> -->
<!--     <= image_tag bscene.image.url %>

    </div>
    < if @projx.user == current_user %>
      <div class="index-post-description">

      <span><= link_to "Delete", [bscene.projx, bscene], method: :delete, data: { confirm: 'Are you sure?' } %></span>

      </div>
    < end %>
    <br />
      </div>
    </div>
    < end %>
  </div>
</div>
</div> -->
















</div>