aystarz52/config/routes.rb
Rails.application.routes.draw do
  resources :projxes do
  	resources :bscenes
  end

  devise_for :users

  root "projxes#index"

  resources :messages, only: [:create, :new, :index]

  resources :users

end

aystarz52/app/models/bscene.rb
class Bscene < ActiveRecord::Base
	belongs_to :projx
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	has_attached_file :video, styles: {
	    :medium => {
	      :geometry => "640x480",
	      :format => 'mp4'
	    },
	    :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 10}
  	}, :processors => [:transcoder]

end

aystarz52/app/models/bscnene.rb
class Bscnene < ActiveRecord::Base
  belongs_to :projx
  belongs_to :user
end

aystarz52/app/models/message.rb
class Message < ActiveRecord::Base
	attr_reader :user_tokens

	belongs_to :sender, class_name: 'User'
	has_many :recipients
	has_many :users, :through => :recipients

	validates :sender_id, presence: true
	validates :title, presence: true
	validates :description, presence: true
	validates :budget, presence: true
	validates :location, presence: true
	validates :date, presence: true
	validates :start_time, presence: true
	validates :end_time, presence: true
	validates :skill, presence: true


	def user_tokens=(ids)
		self.user_ids = ids
	end

end

aystarz52/app/models/projx.rb
class Projx < ActiveRecord::Base
 	belongs_to :user
 	has_many :bscenes, dependent: :destroy
 	acts_as_votable
 	validates :title, :description, :location, :type_skill, :date, presence: true


 #  	validate :user_quota, :on => :create

	# private

	# def user_quota
	# 	if user.projxes.size >= 4
	# 		errors.add(:base, "Exceeds daily limit")
	# 	elsif user.projxes.size <= 10
	# 		errors.add(:base, "Exceeds weekly limit")
	# 	end
	# end

end

aystarz52/app/models/recipient.rb
class Recipient < ActiveRecord::Base
	belongs_to :message
	belongs_to :user

	validates :user_id, presence: true

	after_create :send_recipient_notification

	def send_recipient_notification
		RecipientMailer.recipient_message(user, message).deliver_now
	end
end

aystarz52/app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages, foreign_key: :sender_id
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "50x50#", thumb: "30x30#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  after_create :send_notification
  has_many :projxes
  has_many :bscenes

  def send_notification
  	AdminMailer.new_user(self).deliver_now
  end

end

aystarz52/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :website, :email, :password) }
		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :avatar, :skill, :location, :about, :current_password, :twitter, :facebook, :instagram) }
	end
end

aystarz52/app/controllers/bscenes_controller.rb
class BscenesController < ApplicationController
	before_action :authenticate_user!

	def create
		@projx = Projx.find(params[:projx_id])
		@bscene = @projx.bscenes.create(bscenes_params)

		redirect_to projx_path(@projx)
	end

	def destroy
		@projx = Projx.find params[:projx_id]
		@bscene = @projx.bscenes.find params[:id]
		@bscene.destroy
		redirect_to projx_path(@projx)
	end

	private

	def bscenes_params
		params.require(:bscene).permit(:video)
	end

end

aystarz52/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!, except: [:new]

	def new
		@message = Message.new
		@recipients = User.all
		@recipient = User.find_by(id: params[:to].to_i) if params[:to]
		# @active = params[:active] == 'true' if params[:active].present?
		@chosen_recipient = User.find_by(id: params[:to].to_i) if params[:to]
		@user = User.find_by(id: params[:user])
	end



	def create
		@user = current_user

		@message = current_user.messages.build(message_params)
		if @message.save

			MessageMailer.message_created(@user).deliver_now

			flash[:success] = "Message Sent!"
			redirect_to user_path(@user)
		else
			flash[:alert] = "Nothing Happend!"
			render 'new'
		end
	end

	def index
		@messages = Recipient.where(:user_id => current_user.id).order('created_at DESC')
	end


	private

	def message_params
		params.require(:message).permit(:title, :description, :budget, :location, :date, :userskill, :start_time, :end_time, :skill, :sender_id, user_tokens: [])
	end

end

aystarz52/app/controllers/projxes_controller.rb
class ProjxesController < ApplicationController
  
  before_action :authenticate, except: [:show]

  # GET /projxes
  # GET /projxes.json
  def index
    @projxes = Projx.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
    @users = User.all
  end

  # GET /projxes/1
  # GET /projxes/1.json
  def show
    # @projx = Projx.find(params[:id])
    @projx = Projx.where(created_at: 10.days.ago..Time.now).find(params[:id])
    @bscenes = Bscene.where(projx_id: @projx)
  end

  # GET /projxes/new
  def new
    @projx = current_user.projxes.build
  end

  # GET /projxes/1/edit
  def edit
    @projx = Projx.find(params[:id])
  end

  # POST /projxes
  # POST /projxes.json
  def create
    @projx = current_user.projxes.build(projx_params)
    respond_to do |format|
      if @projx.save
        format.html { redirect_to @projx, notice: 'Projx was successfully created.' }
        format.json { render :show, status: :created, location: @projx }
      else
        format.html { render :new }
        format.json { render json: @projx.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projxes/1
  # PATCH/PUT /projxes/1.json
  def update
    @projx = Projx.find(params[:id])
    respond_to do |format|

      if @projx.update(projx_params)
        format.html { redirect_to @projx, notice: 'Projx was successfully updated.' }
        format.json { render :show, status: :ok, location: @projx }
      else
        format.html { render :edit }
        format.json { render json: @projx.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projxes/1
  # DELETE /projxes/1.json
  def destroy

    @projx = Projx.find(params[:id])
    @user = current_user
    if @projx.destroy
      redirect_to user_path(@user)
    end
  end

  # def upvote
  #   @projx = Projx.find(params[:id])
  #   @projx.upvote_by current_user
  #   redirect_to :back
  # end


  private

  def authenticate
    :authenticate_user! && current_user.try(:admin?)
  end
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
  def projx_params
    params.require(:projx).permit(:title, :type_skill, :location, :description, :website, :date, :stime, :etime, :user_id)
  end
end

aystarz52/app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
end

aystarz52/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@users = User.all
	end

	def show
	  @user = User.find(params[:id])
	end

end

aystarz52/app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

	before_action :authenticate_user!

	def index
	end

end

aystarz52/app/helpers/application_helper.rb
module ApplicationHelper
end

aystarz52/app/helpers/bscenes_helper.rb
module BscenesHelper
end

aystarz52/app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient)
    s = ''

    User.all.each do |user|
      s << "<option value='#{user.id} #{'selected' if user = chosen_recipient}>#{user.username}</option>"
    end
    s = "".html_safe
  end
end

aystarz52/app/helpers/projxes_helper.rb
module ProjxesHelper
end

aystarz52/app/helpers/recipients_helper.rb
module RecipientsHelper
end

aystarz52/app/helpers/users_helper.rb
module UsersHelper
end

aystarz52/app/helpers/welcomes_helper.rb
module WelcomesHelper
end

aystarz52/app/views/bscenes/_bscene.html.erb
<!-- <= bscene.content %> -->

aystarz52/app/views/bscenes/_form.html.erb
<%= form_for([@projx, @projx.bscenes.build]) do |f| %>

	<br />
	<%= f.label :video %>
	<%= f.file_field :video, class: "form-control" %>

<!-- 	<= f.text_field :content, placeholder: "Content" %> -->
	<div class="actions">
		<%= f.submit "Upload Image", class: "btn btn-primary btn-block"  %>
	</div>
<% end %>

aystarz52/app/views/users/show.html.erb
<div class="profile">
	<div class="container">
		<div class="profile-information">
		<h5 class="name">

			<%= image_tag @user.avatar.url(:medium), style: "height:40px;width:40px; border-radius:400px;" %>

			<%= @user.username %><br />
		</h5>

<!-- 		<h6>
			<span class="" aria-hidden="true"></span> <= @user.location %>
		</h6> -->
		</div>
	</div>

<% if @user == current_user %>
	<div class="container">
<!-- 		<= link_to 'Contact', new_message_path(to: @user.id), class: 'btn btn-primary btn-block' %> -->
<div class="btn-group btn-group-justified m-b">

<%= link_to "Settings", edit_user_registration_path, class: "btn btn-info btn-rounded", style: "background: #414245; border-radius:400px 0px 0px 400px;" %>

<%= link_to 'Contact', new_message_path(to: @user.id), class: "btn btn-primary btn-rounded" ,text: "Connecting", style:  "border-radius:0px 400px 400px 0px;" %>
</div>

<!-- 		<= link_to 'Project Proposal', new_message_path(to: @user.id),style: "
		background: #fff;
		color: #3b5998;
		border: 1.7px solid #3b5998;
		border-radius: 1px;
		padding:9px 5px;
		margin-top: 10px;",
		class: 'btn btn-primary btn-block ' %> -->
	</div>
<% else %>
	<div class="container">
<!-- 		<= link_to 'Contact', new_message_path(to: @user.id), class: 'btn btn-primary btn-block' %> -->

<%= link_to 'Contact', new_message_path(to: @user.id), class: "btn btn-primary btn-block" ,text: "Connecting", style:  "border-radius:400px;" %>
</div>
<% end %>
<!-- <div class="container">
	<h6>
	<span class="" aria-hidden="true"></span> <= @user.skill %>
	</h6>
</div> -->

<br />
<div class="container">
<%= @user.about %>
</div>
<br />
<div class="container">
	<h4>Connect</h4>
	<div class="col-md-12">
	    <ul class="social-network social-circle">
<!-- 	    	<li><a href="http://facebook.com/<= @user.facebook, target="_blank" %>" onclick="window.open(this.href); return false;" onkeypress="window.open(this.href); return false;" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li> -->
	       	<li><a href="http://instagram.com/<%= @user.instagram %>" onclick="window.open(this.href); return false;" onkeypress="window.open(this.href); return false;" class="icoInstagram" title="Instagram"><i class="fa fa-instagram"></i></a></li>

	        <li><a href="http://twitter.com/<%= @user.twitter %>" onclick="window.open(this.href); return false;" onkeypress="window.open(this.href); return false;" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
	    </ul>
	</div>
</div>
</div>
<div class ="container">

<div class="col-md-4 col-sm-12 col-xs-12">
	<% @user.projxes.each do |projx| %>
	<hr style="
	margin-top: 0px;
    margin-bottom: 30px;
    border: 0;
    border-top: 1px solid #eeeeee;
" />
	<div class="type_skill">
	  <small style="
	    background-color: #6f5499;
		display: inline;
	    padding: .2em .6em .3em;
	    font-size: 75%;
	    font-weight: 700;
	    line-height: 1;
	    color: #fff;
	    text-align: center;
	    white-space: nowrap;
	    vertical-align: baseline;
	    border-radius: .25em;
	  "><%= projx.type_skill %></small>


	  <% if projx.user == current_user %>
	  <small class="pull-right" style="font-size: 15px;"><%= link_to "", projx_path(projx), method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove" %></small>
	  <% end %>

	</div>

	<section class="panel no-border bg-success">
	<div class="panel-heading no-border container" style="
	    color: #fff;
	"><br />
	<b><%= link_to projx.title, projx_path(projx) %></b>
	</div>
	<div class="panel-body bg-white" style="
	    color: #4d4d4d; padding: 0px 15px 0px 15;
	">
	<div>
		<%= image_tag projx.user.avatar.url(:medium), style: "height:20px;width:20px; border-radius:400px;" %>
		<%= link_to projx.user.username, user_path(@user) %>
	<small class="pull-right"><%= projx.date %></small>
	</div>
	<small><%= projx.location %></small>
	</div>
	</section>

	<% end %>
</div>
</div>