mapapp/config/routes.rb
Rails.application.routes.draw do

  resources :maps do
    resources :comments
  end
  
  root 'maps#index'

end

mapapp/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :map
end

mapapp/app/models/map.rb
class Map < ActiveRecord::Base

	has_many :comments

	validates :title, presence: true, length: { minimum: 5 }
	validates :description, presence: true

end

mapapp/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create

		#this will find the comment with its id
		@map = Map.find(params[:map_id])

		#this will create the  comment in the form
		@comment = @map.comments.create(params[:comment].permit(:name, :description))

		#once the comment is created this wil redirect to the map
		redirect_to map_path(@map)
	end

	def destroy
		@map = Map.find(params[:map_id])
		@comment = @map.comments.find(params[:id])
		@comment.destroy
		
		redirect_to map_path(@map)
	end
end

mapapp/app/controllers/maps_controller.rb
class MapsController < ApplicationController

	def index
		@maps = Map.all.order('created_at DESC')
	end

	def new
		@map = Map.new
	end

	def show
		@map = Map.find(params[:id])
	end

	def create
		@map = Map.new(map_params)
		if @map.save
			redirect_to @map
		else
			render 'new'
		end
	end

	def edit
		@map = Map.find(params[:id])
	end

	def update
		@map = Map.find(params[:id])
		
		if @map.update(params[:map].permit(:title, :description))
			redirect_to map_path(@map)
		else
			render 'edit'
		end
	end

	def destroy
		@map = Map.find(params[:id])
		@map.destroy
		redirect_to root_path
	end

	private

	def map_params
		params.require(:map).permit(:title, :description)
	end
end

mapapp/app/helpers/comments_helper.rb
module CommentsHelper
end

mapapp/app/helpers/maps_helper.rb
module MapsHelper
end

mapapp/app/views/maps/_form.html.erb
<%= simple_form_for @map do |f| %>
	<%= f.input :title %>
	<%= f.input :description %>

	<%= f.submit %>
<% end %>

mapapp/app/views/maps/edit.html.erb
<%= render 'form' %>
<br />
<%= link_to "Back", root_path %>

mapapp/app/views/maps/index.html.erb
<%= link_to "Create New", new_map_path %>

<% @maps.each do |map| %>
<p>
	<h2><%= link_to map.title, map_path(map) %></h2>
</p>
<p>
	Submitted <%= time_ago_in_words(map.created_at) %> ago | 
	<%= link_to "Edit", edit_map_path(map) %> | 
	<%= link_to "Delete", map, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
<p>
	<%= map.description %>
</p>
<% end %>

mapapp/app/views/maps/new.html.erb
<%= render 'form' %>
<br />
<%= link_to 'Cancel', root_path %>

mapapp/app/views/maps/show.html.erb
<h2><%= @map.title %></h2>
<%= @map.description %>
<br />

<h2><%= @map.comments.count %> Comments </h2>
<%= render @map.comments %>

<h3><%= 'Add a comment'%></h3>
<%= render 'comments/form' %>

<br />

<%= link_to 'Back', root_path %>